### ISSUE TITLE
pyfits tests fail with numpy 1.13

### ISSUE THREAD

**Issue by sergiopasra** [spacetelescope/PyFITS#111]
Just for the records:

```
======================================================================
ERROR: pyfits.tests.test_division.TestDivisionFunctions.test_rec_from_string
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILDROOT/pyfits-3.4-5.fc27.x86_64/usr/lib64/python2.7/site-packages/pyfits/tests/test_division.py", line 21, in test_rec_from_string
    ('c3', '>f4'), ('c4', '|i1')]))
  File "/usr/lib64/python2.7/site-packages/numpy/core/records.py", line 820, in array
    return fromstring(obj, dtype, shape=shape, offset=offset, **kwds)
  File "/usr/lib64/python2.7/site-packages/numpy/core/records.py", line 709, in fromstring
    _array = recarray(shape, descr, buf=datastring, offset=offset)
  File "/usr/lib64/python2.7/site-packages/numpy/core/records.py", line 423, in __new__
    strides=strides, order=order)
TypeError: 'float' object cannot be interpreted as an index

======================================================================
ERROR: pyfits.tests.test_image.TestImageFunctions.test_section
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILDROOT/pyfits-3.4-5.fc27.x86_64/usr/lib64/python2.7/site-packages/pyfits/tests/test_image.py", line 340, in test_section
    fs[0].section[:, np.array([True, False, True]), :],
  File "/builddir/build/BUILDROOT/pyfits-3.4-5.fc27.x86_64/usr/lib64/python2.7/site-packages/pyfits/hdu/image.py", line 833, in __getitem__
    data = self._getdata(key)
  File "/builddir/build/BUILDROOT/pyfits-3.4-5.fc27.x86_64/usr/lib64/python2.7/site-packages/pyfits/hdu/image.py", line 852, in _getdata
    data = [self[keys[:idx] + (k,) + keys[idx + 1:]] for k in ks]
  File "/builddir/build/BUILDROOT/pyfits-3.4-5.fc27.x86_64/usr/lib64/python2.7/site-packages/pyfits/hdu/image.py", line 833, in __getitem__
    data = self._getdata(key)
  File "/builddir/build/BUILDROOT/pyfits-3.4-5.fc27.x86_64/usr/lib64/python2.7/site-packages/pyfits/hdu/image.py", line 848, in _getdata
    ks = np.arange(axis, dtype=int)[key]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 3

======================================================================
FAIL: pyfits.tests.test_table.TestTableFunctions.test_mask_array
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILDROOT/pyfits-3.4-5.fc27.x86_64/usr/lib64/python2.7/site-packages/pyfits/tests/test_table.py", line 866, in test_mask_array
    assert str(hdu.data) == "[('NGC1002', 12.3) ('NGC1003', 15.2)]"
AssertionError

----------------------------------------------------------------------
```

**Comment by pllim** [comment]
Thanks for the report. PyFITS is deprecated. Please use [astropy.io.fits](http://docs.astropy.org/en/stable/io/fits/), which is part of [Astropy](http://www.astropy.org/). Astropy has CI testing and all FITS tests are passing there.
